version: '3.8'

services:
  db:
    image: mysql:latest
    restart: unless-stopped
    container_name: mysql-container1
    ports:
      - "9307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: fadel123
      MYSQL_DATABASE: isp_management
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: isp-backend
    restart: always
    ports:
      - "9030:3000"
    depends_on:
      - db
    volumes:
      - ./storage:/app/storage

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: isp-scheduler
    restart: always
    command: ./scheduler
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: isp-frontend
    restart: always
    ports:
      - "9000:80"
    depends_on:
      - backend

volumes:
  mysql_data: